#!/usr/bin/env bash

#export DJANGO_SETTINGS_MODULE=libvirt_dashboard.settings

echo "select 'drop table if exists \"' || tablename || '\" cascade;'
from pg_tables
where schemaname = 'public';" | python2 ./manage.py dbshell | python2 ./manage.py dbshell

echo "drop table django_migrations;" | python2 ./manage.py dbshell

# Reset environment
pkill -f celery
sudo systemctl restart rabbitmq-server
rm -rf caselink/migrations celerybeat-schedule db.sqlite3

# Reset database
python2 ./manage.py makemigrations caselink
python2 ./manage.py migrate

# Start celery worker
celery worker -A libvirt_dashboard -l info -f celery_worker.log --purge --detach

# Start initial database
python2 ./setup_db.py

# Run server
python2 ./manage.py runserver 0.0.0.0:8888
