#!/usr/bin/env bash

#export DJANGO_SETTINGS_MODULE=caselink.settings

function clean_server()
{
    # Reset environment and db
    echo "select 'drop table if exists \"' || tablename || '\" cascade;'
    from pg_tables
    where schemaname = 'public';" | python2 ./manage.py dbshell | python2 ./manage.py dbshell

    sleep 1

    echo "drop table django_migrations;" | python2 ./manage.py dbshell

    sleep 1

    rm -rf celerybeat-schedule db.sqlite3
}

function setup_server()
{
    touch celery_worker.log
    chown nobody:nobody caselink/backups
    chown nobody:nobody celery_worker.log

    # Start initial database
    python2 ./setup_db.py
}


function start_server()
{
    pkill -f celery
    sudo systemctl restart rabbitmq-server

    sudo -u nobody python2 ./manage.py migrate

    # Start celery worker
    sudo -u nobody celery worker -A caselink -n localhost -l info -f celery_worker.log --purge --detach

    # Run server
    sudo -u nobody python2 ./manage.py runserver 0.0.0.0:8888
}

while [ "$1" != "" ]; do
    case $1 in
        --clean )
            clean_server
            setup_server
            ;;
        * )
            echo "
            Usage:
                --clean: Clean up database and enviroment
            "
            exit 1
    esac
    shift
done

start_server
