# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caselink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caselink',
            name='workitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caselinks', to='caselink.WorkItem'),
        ),
    ]
