# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caselink', '0002_auto_20160826_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framework',
            name='components',
        ),
        migrations.AddField(
            model_name='autocase',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='autocases', to='caselink.Component'),
        ),
        migrations.AlterField(
            model_name='autocasefailure',
            name='autocases',
            field=models.ManyToManyField(blank=True, related_name='failures', to='caselink.AutoCase'),
        ),
        migrations.AlterField(
            model_name='document',
            name='components',
            field=models.ManyToManyField(blank=True, to='caselink.Component'),
        ),
    ]
