# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caselink', '0004_auto_20160831_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocase',
            name='end_commit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='autocase',
            name='start_commit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
