# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caselink', '0005_auto_20160912_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocase',
            name='pr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
