# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 06:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('caselink', '0006_autocase_pr'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(1990, 1, 1, 1, 1, 0, 0, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
