# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caselink', '0007_workitem_updated'),
    ]

    operations = [
        migrations.RenameModel("CaseLink", "Linkage")
    ]
