# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caselink', '0008_auto_20161104_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkage',
            name='title',
        ),
    ]
