# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caselink', '0009_remove_linkage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='comment',
            field=models.CharField(blank=True, max_length=65565, null=True),
        ),
    ]
