# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caselink', '0010_workitem_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='jira_id',
            field=models.CharField(blank=True, max_length=65535),
        ),
    ]
