# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caselink', '0011_workitem_jira_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='jira_id',
            field=models.CharField(blank=True, max_length=65535, null=True),
        ),
    ]
