# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-30 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caselink', '0012_auto_20161117_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='changes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='confirmed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
